services:
  - type: web
    name: na2rgo
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000
